"""文案常量统一导出入口。

各子模块的常量统一在此 re-export，保持与旧 prompt.py 相同的导入接口。
"""

from .image_prompts import (
    _IMAGE_PROMPTS_JSON_EXAMPLE,
    _IMAGE_PROMPTS_JSON_EXAMPLE_NO_SD15,
    _IMAGE_PROMPT_MOTION_TAIL,
    _IMAGE_PROMPT_RULE_LIFE_LANDSCAPE,
    _IMAGE_PROMPT_RULE_MYSTERY_LANDSCAPE,
    _IMAGE_PROMPT_RULE_MYSTERY_PORTRAIT,
    _IMAGE_PROMPT_RULE_REALISTIC_PORTRAIT,
    _IMAGE_PROMPT_RULE_SCIENCE_LANDSCAPE,
    _IMAGE_PROMPT_RULE_SCIENCE_PORTRAIT,
    _IMAGE_PROMPT_RULE_SD15,
    _SD15_PROMPT_EN_RULE,
)
from .narration import (
    _MATERIAL_SCRIPT_JSON_EXAMPLE,
    _NARRATION_ONLY_JSON_EXAMPLE,
    _STORYBOARD_JSON_EXAMPLE,
    _STORYBOARD_JSON_EXAMPLE_COMPACT,
    _LIFE_EXPERIENCE_STRUCTURE_RULE,
    _LIFE_NARRATION_LENGTH_RULE,
    _LIFE_NARRATION_VOICE_RULE,
    _MATERIAL_NARRATION_LENGTH_RULE,
    _MYSTERY_NARRATION_LENGTH_RULE,
    _MYSTERY_NARRATION_VOICE_RULE,
    _MYSTERY_STRUCTURE_RULE,
    _NARRATION_ANTI_MEMOIR_RULE,
    _NARRATION_ANTI_REPETITION_RULE,
    _NARRATION_NO_JSON_RULE,
    _NARRATION_VOICE_RULE,
    _SCIENCE_STRUCTURE_RULE,
)
from .visual_brief import _VISUAL_BRIEF_RULE, _VISUAL_BRIEF_JSON_EXAMPLE
